# Generated by Django 5.2.11 on 2026-02-27 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerEmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('home_hero', 'Home - Hero'), ('home_about', 'Home - Sobre'), ('home_services', 'Home - Serviços'), ('home_team', 'Home - Equipe'), ('home_cases', 'Home - Cases'), ('home_cta', 'Home - CTA final'), ('about_main', 'Página Sobre'), ('services_main', 'Página Serviços'), ('team_main', 'Página Equipe'), ('cases_main', 'Página Cases'), ('contact_main', 'Página Contato')], max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='sections/images/')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section_key'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='protected_file',
            field=models.FileField(blank=True, null=True, upload_to='products/files/'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='security_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
