# Generated by Django 5.2.11 on 2026-02-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sectioncontent_instagram_sectioncontent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
