# Generated by Django 5.2.11 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sectioncontent_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("company", models.CharField(blank=True, max_length=150)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("website", "Desenvolvimento de Sites"),
                            ("app", "Aplicativos Mobile"),
                            ("system", "Sistemas Web"),
                            ("automation", "Automações e Integrações"),
                            ("custom", "Projeto sob medida"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Novo"), ("contacted", "Em contato"), ("done", "Finalizado")],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
