# Generated by Django 5.2.11 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontent',
            name='section_key',
            field=models.CharField(choices=[('home_hero', 'Home - Hero'), ('home_about', 'Home - Sobre'), ('home_services', 'Home - Serviços'), ('home_team', 'Home - Equipe'), ('home_cases', 'Home - Cases'), ('home_cta', 'Home - CTA final'), ('about_main', 'Página Sobre'), ('services_main', 'Página Serviços'), ('services_pricing', 'Página Serviços - Preços'), ('team_main', 'Página Equipe'), ('cases_main', 'Página Cases'), ('contact_main', 'Página Contato'), ('profile', 'Perfil (Contato e Redes)')], max_length=80, unique=True),
        ),
    ]
