# Generated by Django 5.2.11 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_servicerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.FileField(upload_to="feedbacks/images/")),
                ("author", models.CharField(blank=True, max_length=150)),
                ("role", models.CharField(blank=True, max_length=150)),
                ("quote", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True, verbose_name="Publicado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
