# Generated by Django 5.2.11 on 2026-03-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_sectioncontent_section_key"),
        ("core", "0006_clientfeedback"),
    ]

    operations = []
