# Generated by Django 5.2.11 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_clientprofile_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="services/images/")),
                ("is_published", models.BooleanField(default=True, verbose_name="Publicado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("result", models.TextField(blank=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="cases/images/")),
                ("is_published", models.BooleanField(default=True, verbose_name="Publicado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
