"""Rotas do app core."""

from django.urls import path

from .views import (
    UdevLoginView,
    UdevLogoutView,
    ManagerLoginView,
    about_view,
    account_view,
    cases_view,
    contact_view,
    case_detail_view,
    docs_view,
    download_product_file_view,
    feedbacks_view,
    guidelines_view,
    home_view,
    manager_dashboard_view,
    manager_case_delete_view,
    manager_case_edit_view,
    manager_member_delete_view,
    manager_member_edit_view,
    manager_password_setup_view,
    manager_product_delete_view,
    manager_product_edit_view,
    manager_service_delete_view,
    manager_service_edit_view,
    manager_token_request_view,
    manager_user_toggle_active_view,
    manager_user_toggle_staff_view,
    member_detail_view,
    rights_view,
    product_detail_view,
    purchase_product_view,
    register_view,
    service_detail_view,
    services_view,
    team_view,
)

urlpatterns = [
    path("", home_view, name="home"),
    path("sobre/", about_view, name="about"),
    path("servicos/", services_view, name="services"),
    path("equipe/", team_view, name="team"),
    path("cases/", cases_view, name="cases"),
    path("cases/<slug:slug>/", case_detail_view, name="case_detail"),
    path("contato/", contact_view, name="contact"),
    path("feedbacks/", feedbacks_view, name="feedbacks"),
    path("documentacao/", docs_view, name="docs"),
    path("direitos/", rights_view, name="rights"),
    path("diretrizes/", guidelines_view, name="guidelines"),
    path("membro/<slug:slug>/", member_detail_view, name="member_detail"),
    path("servicos/<slug:slug>/", service_detail_view, name="service_detail"),
    path("produto/<slug:slug>/", product_detail_view, name="product_detail"),
    path("produto/<slug:slug>/adquirir/", purchase_product_view, name="purchase_product"),
    path("produto/<slug:slug>/download/", download_product_file_view, name="download_product_file"),
    path("login/", UdevLoginView.as_view(), name="login"),
    path("logout/", UdevLogoutView.as_view(), name="logout"),
    path("cadastro/", register_view, name="register"),
    path("conta/", account_view, name="account"),
    path("gestao/token/", manager_token_request_view, name="manager_token_request"),
    path("gestao/ativar/", manager_password_setup_view, name="manager_password_setup"),
    path("gestao/login/", ManagerLoginView.as_view(), name="manager_login"),
    path("gestao/", manager_dashboard_view, name="manager_dashboard"),
    path("gestao/produtos/<int:product_id>/editar/", manager_product_edit_view, name="manager_product_edit"),
    path("gestao/produtos/<int:product_id>/remover/", manager_product_delete_view, name="manager_product_delete"),
    path("gestao/servicos/<int:service_id>/editar/", manager_service_edit_view, name="manager_service_edit"),
    path("gestao/servicos/<int:service_id>/remover/", manager_service_delete_view, name="manager_service_delete"),
    path("gestao/cases/<int:case_id>/editar/", manager_case_edit_view, name="manager_case_edit"),
    path("gestao/cases/<int:case_id>/remover/", manager_case_delete_view, name="manager_case_delete"),
    path("gestao/membros/<int:member_id>/editar/", manager_member_edit_view, name="manager_member_edit"),
    path("gestao/membros/<int:member_id>/remover/", manager_member_delete_view, name="manager_member_delete"),
    path("gestao/usuarios/<int:user_id>/perfil/", manager_user_toggle_staff_view, name="manager_user_toggle_staff"),
    path("gestao/usuarios/<int:user_id>/status/", manager_user_toggle_active_view, name="manager_user_toggle_active"),
]
